version: '3.8'
services:
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: project_20
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - app-network

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=project_20
      - DB_USER=root
      - DB_PASSWORD=root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
