# Generated by Django 5.2.14 on 2026-06-08 06:35

import service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('cgpa', models.FloatField()),
            ],
            options={
                'db_table': 'sos_collegesystem',
            },
            bases=(service.models.DropdownItem, models.Model),
        ),
    ]
