# Generated by Django 5.2.14 on 2026-06-03 10:17

import service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'sos_college',
            },
            bases=(service.models.DropdownItem, models.Model),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('college_id', models.IntegerField(default=0)),
                ('college_name', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'sos_course',
            },
            bases=(service.models.DropdownItem, models.Model),
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('college_id', models.IntegerField()),
                ('college_name', models.CharField(max_length=50)),
                ('subject_id', models.IntegerField()),
                ('subject_name', models.CharField(max_length=50)),
                ('course_id', models.IntegerField()),
                ('course_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_faculty',
            },
            bases=(service.models.DropdownItem, models.Model),
        ),
        migrations.CreateModel(
            name='Marksheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('physics', models.IntegerField()),
                ('chemistry', models.IntegerField()),
                ('maths', models.IntegerField()),
                ('year', models.IntegerField()),
                ('student_id', models.IntegerField()),
            ],
            options={
                'db_table': 'sos_marksheet',
            },
            bases=(service.models.DropdownItem, models.Model),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'sos_role',
            },
            bases=(service.models.DropdownItem, models.Model),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField(blank=True, null=True)),
                ('mobile_number', models.CharField(max_length=20)),
                ('college_id', models.IntegerField()),
                ('college_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_student',
            },
            bases=(service.models.DropdownItem, models.Model),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('course_id', models.IntegerField()),
                ('course_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_subject',
            },
            bases=(service.models.DropdownItem, models.Model),
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('exam_time', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=50)),
                ('course_id', models.IntegerField()),
                ('course_name', models.CharField(max_length=50)),
                ('subject_id', models.IntegerField()),
                ('subject_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_timetable',
            },
            bases=(service.models.DropdownItem, models.Model),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('login', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('dob', models.DateField(max_length=20)),
                ('gender', models.CharField(default='', max_length=50)),
                ('mobile_number', models.CharField(default='', max_length=50)),
                ('role_id', models.IntegerField()),
                ('role_name', models.CharField(max_length=50)),
                ('photo', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'db_table': 'sos_user',
            },
            bases=(service.models.DropdownItem, models.Model),
        ),
    ]
