# Generated by Django 5.2.14 on 2026-06-09 13:54

import service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_collegesystem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_level', models.CharField(max_length=100)),
                ('source_ip', models.CharField(max_length=100)),
                ('detected_time', models.DateField()),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sos_security_alert',
            },
            bases=(service.models.DropdownItem, models.Model),
        ),
    ]
